### ISSUE TITLE
Init command fails on version 2.4.2

### ISSUE THREAD

**Issue by mwebler** [TypedProject/tsed-cli#46]
Hi there! 👋 

I am just starting to try out TsED and I am getting the following error when running the init command (using latest version, 2.4.2):
```
> npx @tsed/cli@ init .
npx: installed 534 in 26.011s
(node:45266) UnhandledPromiseRejectionWarning: Error: option 'version' clashes with existing property 'version' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/commander/index.js:472:13)
    at Command._optionEx (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/commander/index.js:499:10)
    at Command.option (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/commander/index.js:622:17)
    at /Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:131:30
    at Array.reduce (<anonymous>)
    at CliService.buildOption (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:123:33)
    at CliService.build (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:174:22)
    at /Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:38:104
    at Array.forEach (<anonymous>)
    at CliService.load (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:38:77)
    at CliService.parseArgs (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:34:14)
    at Cli.parseArgs (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/Cli.js:81:25)
    at /Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/lib/bin/tsed.js:18:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/matheus/.npm/_npx/45266/lib/node_modules/@tsed/cli/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:45266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This looks like an issue introduced in the latest version of the CLI. 
The previous version, 2.4.1 works just fine:

```
> npx @tsed/cli@2.4.1 init .
npx: installed 527 in 11.78s
? Choose the target platform: (Use arrow keys)
❯ Express.js 
  Koa.js 
```

I tried it out on Node 15, 14 and 12, with the same outcome: v2.4.1 works, v2.4.2 has the exception.

**Comment by Romakita** [comment]
Hello can you retry by installing the cli with:
```
npm install -g @tsed/cli
```
Please,
See you

**Comment by ITninja04** [comment]
@Romakita good morning, I am getting the same error and have just installed the cli for the first time.

```
➜  Projects sudo npm install -g @tsed/cli

npm WARN deprecated highlight.js@9.18.3: Version no longer supported. Upgrade to @latest
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
/usr/local/bin/tsed -> /usr/local/lib/node_modules/@tsed/cli/lib/bin/tsed.js
+ @tsed/cli@2.4.2
updated 1 package in 7.768s
➜  Projects tsed init ./testProject      
(node:1644) UnhandledPromiseRejectionWarning: Error: option 'version' clashes with existing property 'version' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/usr/local/lib/node_modules/@tsed/cli/node_modules/commander/index.js:472:13)
    at Command._optionEx (/usr/local/lib/node_modules/@tsed/cli/node_modules/commander/index.js:499:10)
    at Command.option (/usr/local/lib/node_modules/@tsed/cli/node_modules/commander/index.js:622:17)
    at /usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:131:30
    at Array.reduce (<anonymous>)
    at CliService.buildOption (/usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:123:33)
    at CliService.build (/usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:174:22)
    at /usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:38:104
    at Array.forEach (<anonymous>)
    at CliService.load (/usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:38:77)
    at CliService.parseArgs (/usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:34:14)
    at Cli.parseArgs (/usr/local/lib/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/Cli.js:81:25)
    at /usr/local/lib/node_modules/@tsed/cli/lib/bin/tsed.js:18:13
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@tsed/cli/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➜  Projects node -v
v14.13.1
```

**Comment by Romakita** [comment]
Ok I found the issue. I upgraded commander yesterday. There is issue on it. I'll revert the package until I haven't correctly found the fix :)

**Comment by Romakita** [comment]
Release in progress

**Comment by Romakita** [comment]
Fixed :)
