### ISSUE TITLE
Missing modules at install for passport and jest

### ISSUE THREAD

**Issue by SirNiggo** [TypedProject/tsed-cli#6]
Hi,

first thanks for your awesome work on the TS.ED project. I really appreciate it.

I wanted to try the CLI today but experienced some problems while doing so.
I checked JEST as testing tool and passport.js.

While installing the modules via Yarn, I got errors that thje modules @tsed/cli-plugin-passport and @tsed/cli-plugin-jest were not found.

Is this intended? The modules do exist in the main npm registry.

Please tell me if you need any additional info.

![image](https://user-images.githubusercontent.com/27201677/79636110-a2296500-8175-11ea-8a79-e4ad9908f768.png)

![image](https://user-images.githubusercontent.com/27201677/79636116-abb2cd00-8175-11ea-9030-69c64280780b.png)

Kind Regards

**Comment by Romakita** [comment]
Yes it's strange. I'll check the current CLI version. Maybe something is badly configured since I remove the npm dist-tag beta.
Can you retry with the verbose option to have more details please :) 
```
tsed init . --verbose
```

See you
Romain

**Comment by Romakita** [comment]
Ok found the issue. When I test the CLI, I use 
```
tsed init .
```
Instead of :
```
tsed init  projet-name
```

I'll fix the problem :)

**Comment by SirNiggo** [comment]
@Romakita thank you very much for looking into that! I'll give it a shot asap. Happy to be funding your project again with a few dollars soon again, because you're doing an amazing job with this. :)

**Comment by SirNiggo** [comment]
Here is the verbose output if you still need it:

`C:\Projekte\shinder>tsed init shinder-api --verbose
? What is your project name shinder-api
? Check the features needed for your project Database, File uploading with Multer, Passport.js, Socket.io, Swagger, Testing, Linter
? Choose a ORM manager Mongoose
? Choose unit framework Jest
? Choose linter tools TsLint, Prettier, Lint on commit
[19:15:22] Install plugins [started]
[19:15:22] Resolve versions [started]
[19:15:22] → 0/31 resolved - @tsed/common,@tsed/core,@tsed/di,@tsed/ajv,ajv,body-parser,cors,compression,concurrently,cookie-parser,express,method-override,cross-env,@tsed/multipartfiles,@tsed/passport,@tsed/socketio,@tsed/swagger,@tsed/mongoose,@types/mongoose,mongoose,@types/express,@types/node,@types/compression,@types/cookie-parser,@types/method-override,nodemon,ts-node,typescript,@tsed/testing,@types/supertest,supertest
[19:15:22] → [1/31] Resolving packages...
[19:15:22] → [2/31] Resolving packages...
[19:15:22] → [3/31] Resolving packages...
[19:15:22] → [4/31] Resolving packages...
[19:15:22] → [5/31] Resolving packages...
[19:15:22] → [6/31] Resolving packages...
[19:15:22] → [7/31] Resolving packages...
[19:15:22] → [8/31] Resolving packages...
[19:15:22] → [9/31] Resolving packages...
[19:15:23] → [10/31] Resolving packages...
[19:15:23] → [11/31] Resolving packages...
[19:15:23] → [12/31] Resolving packages...
[19:15:23] → [13/31] Resolving packages...
[19:15:23] → [14/31] Resolving packages...
[19:15:23] → [15/31] Resolving packages...
[19:15:23] → [16/31] Resolving packages...
[19:15:23] → [17/31] Resolving packages...
[19:15:23] → [18/31] Resolving packages...
[19:15:24] → [19/31] Resolving packages...
[19:15:24] → [20/31] Resolving packages...
[19:15:24] → [21/31] Resolving packages...
[19:15:24] → [22/31] Resolving packages...
[19:15:24] → [23/31] Resolving packages...
[19:15:24] → [24/31] Resolving packages...
[19:15:24] → [25/31] Resolving packages...
[19:15:24] → [26/31] Resolving packages...
[19:15:24] → [27/31] Resolving packages...
[19:15:24] → [28/31] Resolving packages...
[19:15:25] → [29/31] Resolving packages...
[19:15:25] → [30/31] Resolving packages...
[19:15:25] → [31/31] Resolving packages...
[19:15:25] → [31/31] Resolving packages...
[19:15:25] Resolve versions [completed]
[19:15:25] Write package.json [started]
[19:15:25] Write package.json [completed]
[19:15:25] Installing dependencies using npm [started]
[19:15:47] → > ejs@3.0.2 postinstall C:\Projekte\shinder\shinder-api\node_modules\ejs
[19:15:47] → > node --harmony ./postinstall.js
[19:15:47] → Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
[19:15:47] → > nodemon@2.0.3 postinstall C:\Projekte\shinder\shinder-api\node_modules\nodemon
[19:15:47] → > node bin/postinstall || exit 0
[19:15:47] → npm notice created a lockfile as package-lock.json. You should commit this file.
[19:15:47] → npm WARN @tsed/multipartfiles@5.46.0 requires a peer of @types/multer@^1.4.2 but none is installed. You must install peer dependencies yourself.
[19:15:47] → npm WARN @tsed/socketio@5.46.0 requires a peer of @types/socket.io@^2.1.4 but none is installed. You must install peer dependencies yourself.
[19:15:47] → npm WARN @tsed/socketio@5.46.0 requires a peer of socket.io@^2.3.0 but none is installed. You must install peer dependencies yourself.
[19:15:47] → npm WARN shinder-api@1.0.0 No description
[19:15:47] → npm WARN shinder-api@1.0.0 No repository field.
[19:15:47] → npm WARN shinder-api@1.0.0 No license field.
[19:15:47] → npm WARN The package concurrently is included as both a dev and production dependency.
[19:15:47] → npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
[19:15:47] → npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[19:15:47] → added 400 packages from 390 contributors and audited 1544 packages in 19.747s
[19:15:47] → 13 packages are looking for funding
[19:15:47] →   run `npm fund` for details
[19:15:47] → found 0 vulnerabilities     
[19:15:47] Installing dependencies using npm [completed]
[19:15:47] Add dependencies using npm [started]
[19:15:47] Add dependencies using npm [skipped]
[19:15:47] Add devDependencies using npm [started]
[19:15:47] Add devDependencies using npm [skipped]
[19:15:47] Clean [started]
[19:15:47] Clean [completed]
[19:15:47] Install plugins [completed]
[19:15:47] Load plugins [started]
[19:15:47] Load plugins [failed]
[19:15:47] → Cannot find module '@tsed/cli-plugin-jest'
Require stack:
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\utils\importModule.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\services\ProjectPackageJson.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\utils\loadPlugins.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\services\CliPlugins.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\commands\AddCmd.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\index.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\lib\bin\tsed.js
(node:25664) UnhandledPromiseRejectionWarning: Error: Cannot find module '@tsed/cli-plugin-jest'
Require stack:
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\utils\importModule.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\services\ProjectPackageJson.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\utils\loadPlugins.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\services\CliPlugins.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\commands\AddCmd.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\index.js
- C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\lib\bin\tsed.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._resolveFilename (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\module-alias\index.js:49:29)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at Object.<anonymous> (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\src\utils\importModule.ts:15:20)
    at Generator.next (<anonymous>)
    at C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\tslib\tslib.js:109:16)
    at Object.importModule (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\lib\utils\importModule.js:7:20)
    at Object.<anonymous> (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\src\utils\loadPlugins.ts:19:39)
    at Generator.next (<anonymous>)
    at C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\tslib\tslib.js:109:16)
    at C:\Users\nicoe\AppData\Roaming\nvm\v12.16.1\node_modules\@tsed\cli\node_modules\@tsed\cli-core\src\utils\loadPlugins.ts:18:22
    at Array.map (<anonymous>)
(node:25664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:25664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Romakita** [comment]
@SirNiggo Thanks :)
The fix will be released in few minutes ;)
Thanks for your report :D

**Comment by Romakita** [comment]
And thanks a lot for your message :D it give me a energy to works on this project and continue to adding features ;)
