### ISSUE TITLE
TypeError: Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by antonio-piha** [TypedProject/tsed-cli#86]
Thanks for amazing project Tsed.  Having cli is also very useful. 👍 

Continuing discussion on this issue because it's still not fixed:
https://github.com/TypedProject/tsed-cli/issues/15

tsed-cli help is still showing providers with first letter uppercase:
```
$tsed --version
2.10.1

$tsed generate --help

Usage: tsed generate|g [options] [type] [name]

Generate a new provider class

Arguments:

  type                   Type of the provider (Injectable, Controller, Pipe, etc...)
...
```

Also when run with something else as a provider it breaks with same error:

```
$tsed generate Schema MyModel
(node:2544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'owner' of undefined
    at ProvidersInfoService.isMyProvider (/path/node_modules/@tsed/cli/lib/services/ProvidersInfoService.js:23:35)
    at GenerateCmd.<anonymous> (/path/node_modules/@tsed/cli/lib/commands/generate/GenerateCmd.js:122:36)
    at Generator.next (<anonymous>)
    at /path/node_modules/@tsed/cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/node_modules/@tsed/cli/node_modules/tslib/tslib.js:113:16)
    at GenerateCmd.$exec (/path/node_modules/@tsed/cli/lib/commands/generate/GenerateCmd.js:120:24)
    at CliService.<anonymous> (/path/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:99:40)
    at Generator.next (<anonymous>)
    at /path/node_modules/@tsed/cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/node_modules/@tsed/cli/node_modules/tslib/tslib.js:113:16)
    at CliService.getTasks (/path/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:92:24)
    at CliService.<anonymous> (/path/node_modules/@tsed/cli/node_modules/@tsed/cli-core/lib/services/CliService.js:52:32)
    at Generator.next (<anonymous>)
    at /path/node_modules/@tsed/cli/node_modules/tslib/tslib.js:117:75
```

Thank you.

**Comment by Romakita** [comment]
Hello @antonio-piha 

Ok I see the error. Schema case is not correct. 

Try:
tsed g schema MyModel

**Comment by antonio-piha** [comment]
Thanks for your response 👍 

Unfortunately getting the same error with that command:
```
$tsed generate schema MyModel
(node:19492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'owner' of undefined
...

From what I can see there's no `schema` type defined in this file:
https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/src/commands/generate/ProviderTypes.ts

This actually worked for schema, `tsed g mongoose:schema mymodel` :
```
tsed g mongoose:schema mymodel
  √ Generate mongoose:schema spec file to 'models/MymodelSchema.spec.ts'
  √ Generate mongoose:schema file to 'models/MymodelSchema.ts'
```

So I had to pass in `mongoose:schema` which I found here:
https://github.com/TypedProject/tsed-cli/blob/master/packages/cli-plugin-mongoose/src/hooks/MongooseGenerateHook.ts#L39

Best solution would be to update cli `help` output to reflect correct usage here:
https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/src/commands/generate/GenerateCmd.ts#L49

But maybe as well to either replace the non-null assertion operator (!) with an if statement or take a different approach, because it's clearly removed from produced javascript code (line which is causing the exception):
https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/src/services/ProvidersInfoService.ts#L34

Also it would be the best to update template for mongoose.schema to replace deprecated decorators:
https://github.com/TypedProject/tsed-cli/blob/master/packages/cli-plugin-mongoose/templates/mongoose.schema.hbs
from
`import { Property } from "@tsed/common";`
to
`import { Property } from "@tsed/schema";`


Thank you.

**Comment by Romakita** [comment]
Hello @antonio-piha 
Thanks for your analyse.

I fixed the issue in this [PR](https://github.com/TypedProject/tsed-cli/pull/87) and added a basic search on the given term for the provider type. 
If the term isn't exact the CLI will propose the nearest matching providers list.

I also fixed the different templates :)

See you
